### PR TITLE
Add Infinite scroll to category feed screen

### PR DESCRIPTION
**Pull request by kwekubright**
### Description:
In this feature, I added infinite scroll to the category feed screen.
This means when the user scrolls to the bottom of the screen, new articles will be fetched and populate. Demo shows this feature on the Africa Category

### Demo

https://user-images.githubusercontent.com/5249414/179892000-0fe47f11-d2c9-4cd4-9559-7108834e0161.mp4

### CODE REVIEW

**Review by niicode — CHANGES_REQUESTED** [review]
# Congratulations🕺: 

Hi @kwekubright   :wave: 
Good job so far! I know you worked hard to implement this feature, I really appreciate the effort you put in! There is nothing else done to merge! 🎉
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@niicode ](https://github.com/niicode) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

**Comment by niicode** [comment]
The feature you worked on only loads infinitely on the Africa feed on the home page but not on the Africa category on the feeds page. I think you should take a look at that

**Review by niicode — APPROVED** [review]

**Review by niicode — APPROVED** [review]

**Review by Graycemuthui — APPROVED** [review]
# Hi @kwekubright ,

# STATUS: APPROVED! 🥇 💯 
### Amazing work on the scroll feature!


done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------

**Comment by kwekubright** [comment]
Thanks @niicode @Graycemuthui 🤗

**Pull request merged**
